### PR TITLE
Add pytest

### PR DESCRIPTION
**Pull request by abraha2d**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by abraha2d** [comment]
@conda-forge-admin, please rerender

**Comment by glenn-jocher** [comment]
@abraha2d it looks like one of the reasons for the tests failures is that git is not available, i.e.:

Screenshot 2023-09-10 at 23 24 42

Should we add git to the testing requirements?

**Comment by glenn-jocher** [comment]
@abraha2d we would need to do something like this since we can't install git with pip:

```
sudo apt-get update
sudo apt-get install git
```

**Comment by glenn-jocher** [comment]
@abraha2d got this working in https://github.com/conda-forge/ultralytics-feedstock/pull/71

Thanks for the help! :)

**Pull request closed without merging**
